### ISSUE TITLE
hum não lista nada

### ISSUE THREAD

**Issue by sergiomb2** [enen92/script.retrogames#1]
Olá , instalei este add-on , num  kodi-14.2-1.fc21.x86_64 mas quando escolho uma categoria, exemplo dosbox depois não lista nenhum jogo nem o search retorna algum resultado .

Obrigado

**Comment by enen92** [comment]
Usa o irl -> http://forum.kodi.tv/showthread.php?tid=231339
Este plugin já é antigo, é provavel que o site tenha mudado.
